import Header from "../components/header"
import Footer from "../components/footer"
import Head from 'next/head'




export default function Format({children}) {
  return (
    <>
        <Head>
        <title>The Holiday Cafe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <main>{children}</main>
        <Footer />
    </>
  )
}
